accounts/urls.py
from django.conf.urls import url
from . import views
app_name = 'accounts'
urlpatterns=[
    url(r'^register/$', views.register, name='register'),
    url(r'^logout/$',views.user_logout,name='logout'),
    url(r'^profile/(?P<pk>\d+)/$', views.ProfileDetailView.as_view(), name='profile'),
#url(r'^profile/(?P<pk>\d+)/edit/$', views.profile_update, name='edit_profile'),
]

heart_disease_prediction/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include

from accounts import views
from heart_disease_prediction import settings

from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$',views.user_login,name='user_login'),
    url(r'^accounts/',include('accounts.urls')),
    url(r'^predict/',include('predict_risk.urls')),
    url(r'^predict_1/',include('predict_risk_1.urls')),
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

predict_risk/urls.py
from django.conf.urls import url
from . import views
app_name='predict'
urlpatterns=[
url(r'^(?P<pk>\d+)$',views.PredictRisk,name='predict')
]

predict_risk_1/urls.py
from django.conf.urls import url
from . import views
app_name='predict_1'
urlpatterns=[
url(r'^(?P<pk>\d+)$',views.PredictRisk_1,name='predict_1')
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf.urls import url
from django.shortcuts import resolve_url


class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    profile_pic = models.ImageField(upload_to='profile_pics', default="1.jpg")

    def __str__(self):
        return self.user.username

# Create your models here.

accounts/forms.py
from django import forms
from .models import UserProfileInfo
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    username = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Enter username'}
    ), required=True, max_length=50)

    email = forms.CharField(widget=forms.EmailInput(
        attrs={'class': 'form-control', 'placeholder': 'Enter Email Id'}
    ), required=True, max_length=50)

    password = forms.CharField(widget=forms.PasswordInput(
        attrs={'class': 'form-control', 'placeholder': 'Enter password'}
    ), required=True, max_length=50)

    confirm_password = forms.CharField(widget=forms.PasswordInput(
        attrs={'class': 'form-control', 'placeholder': 'Confirm password'}
    ), required=True, max_length=50)

    class Meta:
        model = User
        fields = ('username', 'email', 'password')

    def clean(self):
        cleaned_data = super(UserForm, self).clean()
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")

        if password != confirm_password:
            raise forms.ValidationError(
                "Password and Confirm password does not match"
            )


class UserProfileInfoForm(forms.ModelForm):
    class Meta:
        model = UserProfileInfo
        fields = ('profile_pic',)


class UpdateProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')
        widgets = {'username': forms.TextInput(attrs={'readonly': 'True'})}

accounts/views.py
from django.shortcuts import render
from .forms import UserForm, UserProfileInfoForm, UpdateProfileForm
from django.views.generic import DetailView,UpdateView,TemplateView
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from .models import UserProfileInfo, User
from django.shortcuts import get_object_or_404
# Create your views here.

flag=False

@login_required
def user_logout(request):
    #del request.session['user_id']
    request.session.flush()
    logout(request)
    return HttpResponseRedirect(reverse('user_login'))




def register(request):

    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True

        else:
            print(user_form.errors, profile_form.errors)

        if registered:
            return HttpResponseRedirect(reverse('user_login'))

    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request, 'accounts/register.html',{'user_form': user_form, 'profile_form': profile_form, 'registered': registered})


def user_login(request):
    global flag

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        switch = request.POST.get('switch')
        if (switch)=="Heart":
            flag=True
        else:
            flag=False

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                request.session['user_id'] = user.profile.pk

                if (switch) == 'Heart':
                    return HttpResponseRedirect(reverse('predict:predict', kwargs={'pk': user.profile.pk}))
                elif (switch) == 'Kidney':
                    return HttpResponseRedirect(reverse('predict_1:predict_1', kwargs={'pk': user.profile.pk}))
                else:
                    return render(request, 'accounts/login.html', {})

            else:
                return HttpResponse("Account not active")
        else:
            print("Tried login and failed")
            print("username: {} and password: {}".format(username, password))
            return HttpResponse("Invalid login details supplied!")

    else:
        return render(request, 'accounts/login.html', {})

class ProfileDetailView(LoginRequiredMixin, DetailView):
    login_url = '/'
    redirect_field_name = '/'
    model = UserProfileInfo
    template_name = 'accounts/profileview.html'

    def get_context_data(self, **kwargs):
        if self.request.session.has_key('user_id'):
            u_id = self.request.session['user_id']
            context = super(ProfileDetailView, self).get_context_data(**kwargs)
            context['user_id'] = u_id
            context['flag']=flag

        return context

accounts/templates/accounts/login.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
    <meta charset="utf-8">
    <link href="{% static 'css/style.css' %}" rel="stylesheet" />

    <link href="{% static 'css/now-ui-kit.css' %}" rel="stylesheet" />
    <link href='//fonts.googleapis.com/css?family=Open+Sans:400,300,600,700,800' rel='stylesheet' type='text/css'><!--web font-->
    <title>Heart disease prediction</title>
</head>
<body style="background-image: url('{% static 'images/2.jpg' %}')">
	<!-- main -->
	<div class="agileits-main">
	<div class="w3top-nav">

				<div class="w3top-nav-left">
					<h1 style="color:white;">          Heart/Kidney Disease Prediction System</h1>
				</div>

				<div class="w3top-nav-right">
					<ul>

						<li><a href="{% url 'accounts:register' %}">Signup</a></li>
						<li><a href="/admin">Admin login</a></li>
					</ul>
				</div>

		</div>

    <div class="header-main">
      {%if user.is_authenticated %}
        <h2>You are already logged in !!</h2>
        <button class="btn btn-neutral"><a href="{% url 'accounts:logout'%}">Logout</a></button>
      {%else%}
    <h2>Login Now</h2>
			<div class="header-bottom">
				<div class="header-right w3agile">
					<div class="header-left-bottom agileinfo">
            <form role="form" action=" {% url 'user_login' %}" method="post">
            {% csrf_token %}
							<div class="icon1">
								<input type="text" name="username" placeholder="Username" >
							</div>
							<div class="icon1">
								<input type="password"  name="password" placeholder="Password"/>
							</div>
				               <div class="icon1">
								   <!--<select name="switch">-->
									   <!--<option value="Heart">Heart</option>-->
									   <!--<option value="Kidney">Kidney</option>-->
								   <!--</select>-->
								   <input type="text" name="switch" placeholder="Heart/Kidney">
							</div>
							<div class="bottom">
								<input type="submit" value="Log in">
							</div>
					</form>&nbsp;

					</div>
				</div>
			</div>
	</div>

	</div>
	<!-- //main -->
  {% endif %}
</body>

</html>

accounts/templates/accounts/profileview.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" />
    <link href="{% static 'css/now-ui-kit.css' %}" rel="stylesheet" />


    <meta charset="UTF-8">
    <title></title>

</head>

<body class="profile-page sidebar-collapse">
 <nav class="navbar navbar-expand-lg bg-primary fixed-top navbar-transparent" color-on-scroll="400" >
        <div class="container">
            <div class="collapse navbar-collapse justify-content-end" id="navigation" data-nav-image="">
                <ul class="nav nav-tabs" data-tabs="tabs">


                    <li class="nav-item">
                        {% if flag %}
                        <a href="{% url 'predict:predict' pk=user_id %}" class="btn btn-neutral">Predict</a>
                        {%else%}
                        <a href="{% url 'predict_1:predict_1' pk=user_id %}" class="btn btn-neutral">Predict</a>
                        {%endif%}
                    </li>
                    <li class="nav-item">
                      <a href="{% url 'accounts:logout'%}"  class="btn btn-neutral">Logout</a>
                    </li>

                </ul>
            </div>
        </div>
    </nav>
    <div class="wrapper">
        <div class="page-header page-header-small" filter-color="orange" style="max-height: 100px;">
            <div class="page-header-image" data-parallax="true" style="background-image: url('{% static 'img/image1.jpg' %}'); ">
            </div>
            <div class="container">
                <div class="content-center">
                    <div class="photo-container">
                        <img src="{{userprofileinfo.profile_pic.url}}" />
                    </div>
                    <h3 class="title">{{ userprofileinfo.user.username }}</h3>
                    <p class="h5">{{ userprofileinfo.user.email }}</p>


                    </div>
                </div>
            </div>
        </div>

    <div class="section">
            <div class="container">
                <div class="button-container">

                        <i class="fa fa-github"></i>
                    </a>

                </div>
            </div>
    </div>
    <div class="container">
    <div class="card-header bg-warning btn-round text-white">Predictions</div>
        <hr>


        {% for pred in userprofileinfo.predict.all  %}
            <br>

             <div class="card card-login" style="width: 100%">
                    <div class="card-header bg-dark text-white" style="height: 50px;"> Prediction : {{ pred.num|safe}}
                    </div>
                    <div class="container">
                        <br>
                        <p>Age: {{pred.age}}</p>
                        <p>Sex: {{pred.sex}}</p>
                    </div>
                    <div class="card-footer bg-light" >Predicted on {{ pred.predicted_on }}</div>

            </div>
            <br>
        {% endfor %}


    </div>

</body>
<script src="{% static 'js/jquery.3.2.1.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/popper.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/bootstrap_ui_kit.js' %}" type="text/javascript"></script>
</html>

accounts/templates/accounts/register.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
  <meta charset="utf-8">
    <title></title>
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" />
    <link href="{% static 'css/now-ui-kit.css' %}" rel="stylesheet" />



  </head>
  <body>

    <div class="section section-signup" style="background-image: url('{% static 'images/image 3.jpg' %}');-webkit-background-size: cover;-moz-background-size: cover;-o-background-size: cover;background-repeat: no-repeat; background-size: cover; background-position: top center; min-height: 700px;">

      <nav class="navbar navbar-expand-lg  fixed-top navbar-transparent" >
              <div class="container">
                  <div class="collapse navbar-collapse justify-content-end" id="navigation" >
                      <ul class="navbar-nav nav-tabs">



                          {%if user.is_authenticated%}
                            <li class="nav-item"><a  href="{% url 'accounts:logout'%}" class="btn btn-neutral">Logout</a></li>
                            {%else%}
                            <li><a href="{% url 'user_login'  %}" class="btn btn-neutral">Login</a></li>
                            {%endif%}
                            <li class="nav-item"><a href="/admin" class="btn btn-neutral">Admin login</a></li>

                      </ul>
                  </div>
              </div>
          </nav>

    <div class="container" >
			<div class="row">
      <div class="card-signup card-plain" data-background-color="">


          {% if registered %}

          <h1>Thank you for registering!</h1>

          {% else %}

          <form role="form" enctype="multipart/form-data" method="post">
              {% csrf_token %}
              <div class="card-header text-center form-group">
							<h3 class="card-title title-up ">Sign Up</h3>

              {{ user_form}}
              {{ profile_form}}


            <button type="submit" class="btn btn-round bg-transparent border">Sign Up</button>
              </div>
          </form>
          {% endif %}
              </div>
    </div>
  </div>
</div>
  </div>
</div>
</body>
</html>