accounts/urls.py
from django.conf.urls import url
from . import views
app_name = 'accounts'
urlpatterns=[
    url(r'^register/$', views.register, name='register'),
    url(r'^logout/$',views.user_logout,name='logout'),
    url(r'^profile/(?P<pk>\d+)/$', views.ProfileDetailView.as_view(), name='profile'),
#url(r'^profile/(?P<pk>\d+)/edit/$', views.profile_update, name='edit_profile'),
]

heart_disease_prediction/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include

from accounts import views
from heart_disease_prediction import settings

from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$',views.user_login,name='user_login'),
    url(r'^accounts/',include('accounts.urls')),
    url(r'^predict/',include('predict_risk.urls')),
    url(r'^predict_1/',include('predict_risk_1.urls')),
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

predict_risk/urls.py
from django.conf.urls import url
from . import views
app_name='predict'
urlpatterns=[
url(r'^(?P<pk>\d+)$',views.PredictRisk,name='predict')
]

predict_risk/models.py
from django.db import models
from accounts.models import UserProfileInfo
from django.utils import timezone
from django.urls import reverse
# Create your models here.
sex_choices=((0, 'Female'),(1, 'Male'))
cp_choice=((0,'None'),(1, 'Typical Angina'),(2, 'Atypical Angina'),(3, 'Non-Angina'),(4, 'Asymptomatic'))
fasting_blood_sugar_choices=((1,'> 120 mg/dl'),((0,'< 120 mg/dl')))
resting_ecg_choices=((0, 'Normal'),(1, 'Having ST-T wave abnormality'),(2, 'hypertrophy'))
exercise_induced_angina_choices=((0, 'No'),(1, 'Yes'))
st_slope_choices=((1, 'Upsloping'),(2, 'Flat'),(3, 'Down Sloping'))
number_of_vessels_choices=((0, 'None'),(1, 'One'),(2, 'Two'),(3, 'Three'))
thallium_scan_results_choices=((3, 'Normal'),(6, 'Fixed Defect'),(7, 'Reversible Defect'))

class Predictions(models.Model):
    profile = models.ForeignKey(UserProfileInfo, on_delete=models.CASCADE, related_name='predict')
    age = models.IntegerField()
    sex = models.IntegerField(choices=sex_choices, default=0)
    cp = models.IntegerField(choices=cp_choice,default=0)
    resting_bp = models.IntegerField()
    serum_cholesterol = models.IntegerField()
    fasting_blood_sugar = models.IntegerField(choices=fasting_blood_sugar_choices,default=0)
    resting_ecg = models.IntegerField(choices=resting_ecg_choices,default=0)
    max_heart_rate = models.IntegerField()
    exercise_induced_angina = models.IntegerField(choices=exercise_induced_angina_choices,default=0)
    st_depression = models.DecimalField(max_digits=4, decimal_places=2)
    st_slope = models.IntegerField(choices=st_slope_choices)
    number_of_vessels = models.IntegerField(choices=number_of_vessels_choices)
    thallium_scan_results = models.IntegerField(choices=thallium_scan_results_choices)
    predicted_on = models.DateTimeField(default=timezone.now)
    num=models.IntegerField()

    def get_absolute_url(self):
        return reverse('predict:predict', kwargs={'pk': self.profile.pk})

predict_risk/forms.py
from django import forms
from predict_risk.models import Predictions

class Predict_Form(forms.ModelForm):
    class Meta:
        model = Predictions
        fields = ('age','sex','cp','resting_bp','serum_cholesterol','fasting_blood_sugar','resting_ecg','max_heart_rate',
        'exercise_induced_angina','st_depression','st_slope','number_of_vessels','thallium_scan_results')
        widgets = {'age': forms.TextInput(attrs={'class': 'form-control'}),
                   'sex': forms.Select(attrs={'class': 'form-control'}),
                   'cp': forms.Select(attrs={'class': 'form-control'}),
                   'resting_bp':forms.TextInput(attrs={'class': 'form-control'}),
                   'serum_cholesterol':forms.TextInput(attrs={'class': 'form-control'}),
                   'fasting_blood_sugar':forms.Select(attrs={'class': 'form-control'}),
                   'resting_ecg':forms.Select(attrs={'class': 'form-control'}),
                   'max_heart_rate':forms.TextInput(attrs={'class': 'form-control'}),
                   'exercise_induced_angina':forms.Select(attrs={'class': 'form-control'}),
                   'st_depression':forms.TextInput(attrs={'class': 'form-control'}),
                   'st_slope':forms.Select(attrs={'class': 'form-control'}),
                   'number_of_vessels':forms.Select(attrs={'class': 'form-control'}),
                   'thallium_scan_results':forms.Select(attrs={'class': 'form-control'}),
                   }

predict_risk/views.py
import csv,io
from django.shortcuts import render
from .forms import Predict_Form
from predict_risk.data_provider import *
from accounts.models import UserProfileInfo
from django.shortcuts import get_object_or_404, redirect, render
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.decorators import login_required,permission_required
from django.urls import reverse
from django.contrib import messages

@login_required(login_url='/')
def PredictRisk(request,pk):
    predicted = False
    predictions={}
    if request.session.has_key('user_id'):
        u_id = request.session['user_id']

    if request.method == 'POST':
        form = Predict_Form(data=request.POST)
        profile = get_object_or_404(UserProfileInfo, pk=pk)

        if form.is_valid():
            features = [[ form.cleaned_data['age'], form.cleaned_data['sex'], form.cleaned_data['cp'], form.cleaned_data['resting_bp'], form.cleaned_data['serum_cholesterol'],
            form.cleaned_data['fasting_blood_sugar'], form.cleaned_data['resting_ecg'], form.cleaned_data['max_heart_rate'], form.cleaned_data['exercise_induced_angina'],
            form.cleaned_data['st_depression'], form.cleaned_data['st_slope'], form.cleaned_data['number_of_vessels'], form.cleaned_data['thallium_scan_results']]]

            print("Before------",features)
            standard_scalar = GetStandardScalarForHeart()
            features = standard_scalar.transform(features)
            print("Hell0-------",features)
            SVCClassifier,LogisticRegressionClassifier,NaiveBayesClassifier,DecisionTreeClassifier,NeuralNetworkClassifier,KNNClassifier=GetAllClassifiersForHeart()


            predictions = {'SVC': str(SVCClassifier.predict(features)[0]),
            'LogisticRegression': str(LogisticRegressionClassifier.predict(features)[0]),
             'NaiveBayes': str(NaiveBayesClassifier.predict(features)[0]),
             'DecisionTree': str(DecisionTreeClassifier.predict(features)[0]),
              'NeuralNetwork': str(NeuralNetworkClassifier.predict(features)[0]),
              'KNN': str(KNNClassifier.predict(features)[0]),
              }
            pred = form.save(commit=False)

            l=[predictions['SVC'],predictions['LogisticRegression'],predictions['NaiveBayes'],predictions['DecisionTree'],predictions['NeuralNetwork'],predictions['KNN']]
            count=l.count('1')

            result=False

            if count>=3:
                result=True
                pred.num=1
            else:
                pred.num=0

            pred.profile = profile

            pred.save()
            predicted = True

            colors={}

            if predictions['SVC']=='0':
                colors['SVC']="table-success"
            elif predictions['SVC']=='1':
                colors['SVC']="table-danger"

            if predictions['LogisticRegression']=='0':
                colors['LR']="table-success"
            else:
                colors['LR']="table-danger"

            if predictions['NaiveBayes']=='0':
                colors['NB']="table-success"
            else:
                colors['NB']="table-danger"

            if predictions['DecisionTree']=='0':
                colors['DT']="table-success"
            else:
                colors['DT']="table-danger"

            if predictions['NeuralNetwork']=='0':
                colors['NN']="table-success"
            else:
                colors['NN']="table-danger"

            if predictions['KNN']=='0':
                colors['KNN']="table-success"
            else:
                colors['KNN']="table-danger"

    if predicted:
        return render(request, 'predict.html',
                      {'form': form,'predicted': predicted,'user_id':u_id,'predictions':predictions,'result':result,'colors':colors})

    else:
        form = Predict_Form()

        return render(request, 'predict.html',
                      {'form': form,'predicted': predicted,'user_id':u_id,'predictions':predictions})

predict_risk/templates/predict.html
<!DOCTYPE html>
{% load staticfiles %}

<html>
<head>
<title>Medical Emergency Form a Responsive Widget Template :: w3layouts</title>

<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
<script src="http://netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>

<link href="{% static 'css/style2.css' %}" rel="stylesheet" />

<link href="//fonts.googleapis.com/css?family=Roboto:300,400,500,700" rel="stylesheet">
<link href="//fonts.googleapis.com/css?family=Droid+Sans:400,700" rel="stylesheet">
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" />
<link href="{% static 'css/now-ui-kit.css' %}" rel="stylesheet" />
<link href="{% static 'css/medium-editor.min.css' %}" rel="stylesheet">
<!--//fonts-->
</head>
<body style="background-image: url('{% static 'images/2.jpg' %}')">
<!--background-->
<nav class="navbar navbar-expand-lg navbar-transparent" >
        <div class="container">
            <div class="collapse navbar-collapse justify-content-end" id="navigation" >
                <ul class="navbar-nav nav-tabs">

                    <li class="nav-item"><a href="{% url 'accounts:profile' pk=user_id %}" class="btn btn-neutral">Profile</a></li>
                      <li class="nav-item"><a href="{% url 'accounts:logout' %}" class="btn btn-neutral">Logout</a></li>

                </ul>
            </div>
        </div>
    </nav>
<h1>Predict your Heart disease</h1>
    <div class="bg-agile">
	<div class="book-appointment">
	<h2>Medical Information</h2>

  {% if predicted %}
<div class="card" role="alert">
<div class="header-main">
{% if result %}
<h4 class="table-danger text-center">You have a risk of heart disease</h4>
{% else %}
<h4 class="table-success  text-center">You do not have a risk of heart disease</h4>
{% endif %}
</div>
<div class="card-body">
      <div class="table-responsive justify-content-center">
                       <table class="table">
                           <thead>
                               <tr>
                                   <th>Algorithm</th>
                                   <th>Risk of Heart Disease</th>
                               </tr>
                           </thead>
                           <tbody>
                               <tr class="{{colors.LR}}">
                                   <td>Logistic Regression</td>
                                   <td>{{predictions.LogisticRegression}}</td>
                               </tr>
                               <tr class={{colors.SVC}}>
                                   <td>Support Vector Classifier</td>
                                   <td>{{predictions.SVC}}</td>
                               </tr>
                               <tr class={{colors.NB}}>
                                   <td>Naive Bayes</td>
                                   <td>{{predictions.NaiveBayes}}</td>
                               </tr>
                               <tr class={{colors.DT}}>
                                   <td>Decision Tree</td>
                                   <td>{{predictions.DecisionTree}}</td>
                               </tr>
                               <tr class={{colors.NN}}>
                                   <td>Neural Network</td>
                                   <td>{{predictions.NeuralNetwork}}</td>
                               </tr>

                               <tr class={{colors.KNN}}>
                                   <td>KNN</td>
                                   <td>{{predictions.KNN}}</td>
                               </tr>
                           </tbody>

                       </table>
                   </div>
               </div>
             </div>

  {% endif %}

			<form method="post">
        {% csrf_token %}
        <div class="left-agileits-w3layouts same">
          <div class="gaps">
            <p>Age<p>
            {{form.age}}
          </div>

					<div class="gaps">
						<p>Gender</p>
							{{form.sex}}
					</div>

          <div class="gaps">
            <p>Chest Pain</p>
              {{form.cp}}
          </div>

					<div class="gaps">
						<p>Resting BP</p>
							{{form.resting_bp}}
					</div>

					<div class="gaps">
						<p>Serum Cholestrol</p>
							{{form.serum_cholesterol}}
					</div>

					<div class="gaps">
						<p>Fasting Blood Sugar</p>
						   {{form.fasting_blood_sugar}}
					</div>

					<div class="gaps">
						<p>Resting  Electrocardiographic Result</p>
						{{form.resting_ecg}}
					</div>

					<div class="gaps">
						<p>Maximum Heart Rate</p>
						{{form.max_heart_rate}}
					</div>

					<div class="gaps">
						<p>Excercise Induced Angina</p>
						{{form.exercise_induced_angina}}
					</div>

					<div class="gaps">
						<p>ST Depression</p>
						{{form.st_depression}}
					</div>

				</div>

				<div class="right-agileinfo same">

          <div class="gaps">
						<p>Slope of the peak exercise ST segment </p>
				      {{form.st_slope}}
					</div>

          <div class="gaps">
            <p>Number of major vessels (0-3) colored by flourosopy</p>
              {{form.number_of_vessels}}
          </div>

          <div class="gaps">
            <p>Thalium Scan Results</p>
              {{form.thallium_scan_results}}
          </div>

				</div>

				<div class="clear"></div>
				<input type="submit" value="Predict" class="btn btn-primary">
			</form>
		</div>
   </div>
   <!--copyright-->

		<!--//copyright-->
		<script type="text/javascript" src="js/jquery-2.1.4.min.js"></script>
		<!-- Calendar -->
				<link rel="stylesheet" href="css/jquery-ui.css" />
				<script src="js/jquery-ui.js"></script>

			<!-- //Calendar -->

</body>
</html>